/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as MeusCartoesRouteImport } from './routes/meus-cartoes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as AgendarBarbeiroIdRouteImport } from './routes/agendar.$barbeiroId'
import { Route as PagamentoConfirmadoAppointmentIdRouteImport } from './routes/pagamento-confirmado.$appointmentId'
import { Route as PagamentoAppointmentIdRouteImport } from './routes/pagamento.$appointmentId'
import { Route as ApiPublicMercadopagoCardsRouteImport } from './routes/api/public/mercadopago-cards'
import { Route as ApiPublicMercadopagoOauthRouteImport } from './routes/api/public/mercadopago-oauth'
import { Route as ApiPublicMercadopagoPixRouteImport } from './routes/api/public/mercadopago-pix'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCartoesRoute = MeusCartoesRouteImport.update({
  id: '/meus-cartoes',
  path: '/meus-cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarBarbeiroIdRoute = AgendarBarbeiroIdRouteImport.update({
  id: '/agendar/$barbeiroId',
  path: '/agendar/$barbeiroId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmadoAppointmentIdRoute =
  PagamentoConfirmadoAppointmentIdRouteImport.update({
    id: '/pagamento-confirmado/$appointmentId',
    path: '/pagamento-confirmado/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagamentoAppointmentIdRoute = PagamentoAppointmentIdRouteImport.update({
  id: '/pagamento/$appointmentId',
  path: '/pagamento/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoCardsRoute =
  ApiPublicMercadopagoCardsRouteImport.update({
    id: '/api/public/mercadopago-cards',
    path: '/api/public/mercadopago-cards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoOauthRoute =
  ApiPublicMercadopagoOauthRouteImport.update({
    id: '/api/public/mercadopago-oauth',
    path: '/api/public/mercadopago-oauth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoPixRoute = ApiPublicMercadopagoPixRouteImport.update({
  id: '/api/public/mercadopago-pix',
  path: '/api/public/mercadopago-pix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/meus-cartoes': typeof MeusCartoesRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-cards': typeof ApiPublicMercadopagoCardsRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-pix': typeof ApiPublicMercadopagoPixRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/meus-cartoes': typeof MeusCartoesRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-cards': typeof ApiPublicMercadopagoCardsRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-pix': typeof ApiPublicMercadopagoPixRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/meus-cartoes': typeof MeusCartoesRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-cards': typeof ApiPublicMercadopagoCardsRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-pix': typeof ApiPublicMercadopagoPixRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/meus-cartoes'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-cards'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-pix'
    | '/api/public/mercadopago-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/meus-cartoes'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-cards'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-pix'
    | '/api/public/mercadopago-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/meus-cartoes'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-cards'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-pix'
    | '/api/public/mercadopago-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  MeusCartoesRoute: typeof MeusCartoesRoute
  PainelRoute: typeof PainelRoute
  AgendarBarbeiroIdRoute: typeof AgendarBarbeiroIdRoute
  PagamentoConfirmadoAppointmentIdRoute: typeof PagamentoConfirmadoAppointmentIdRoute
  PagamentoAppointmentIdRoute: typeof PagamentoAppointmentIdRoute
  ApiPublicMercadopagoCardsRoute: typeof ApiPublicMercadopagoCardsRoute
  ApiPublicMercadopagoOauthRoute: typeof ApiPublicMercadopagoOauthRoute
  ApiPublicMercadopagoPixRoute: typeof ApiPublicMercadopagoPixRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-cartoes': {
      id: '/meus-cartoes'
      path: '/meus-cartoes'
      fullPath: '/meus-cartoes'
      preLoaderRoute: typeof MeusCartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$barbeiroId': {
      id: '/agendar/$barbeiroId'
      path: '/agendar/$barbeiroId'
      fullPath: '/agendar/$barbeiroId'
      preLoaderRoute: typeof AgendarBarbeiroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado/$appointmentId': {
      id: '/pagamento-confirmado/$appointmentId'
      path: '/pagamento-confirmado/$appointmentId'
      fullPath: '/pagamento-confirmado/$appointmentId'
      preLoaderRoute: typeof PagamentoConfirmadoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$appointmentId': {
      id: '/pagamento/$appointmentId'
      path: '/pagamento/$appointmentId'
      fullPath: '/pagamento/$appointmentId'
      preLoaderRoute: typeof PagamentoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-cards': {
      id: '/api/public/mercadopago-cards'
      path: '/api/public/mercadopago-cards'
      fullPath: '/api/public/mercadopago-cards'
      preLoaderRoute: typeof ApiPublicMercadopagoCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-oauth': {
      id: '/api/public/mercadopago-oauth'
      path: '/api/public/mercadopago-oauth'
      fullPath: '/api/public/mercadopago-oauth'
      preLoaderRoute: typeof ApiPublicMercadopagoOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-pix': {
      id: '/api/public/mercadopago-pix'
      path: '/api/public/mercadopago-pix'
      fullPath: '/api/public/mercadopago-pix'
      preLoaderRoute: typeof ApiPublicMercadopagoPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  MeusCartoesRoute: MeusCartoesRoute,
  PainelRoute: PainelRoute,
  AgendarBarbeiroIdRoute: AgendarBarbeiroIdRoute,
  PagamentoConfirmadoAppointmentIdRoute: PagamentoConfirmadoAppointmentIdRoute,
  PagamentoAppointmentIdRoute: PagamentoAppointmentIdRoute,
  ApiPublicMercadopagoCardsRoute: ApiPublicMercadopagoCardsRoute,
  ApiPublicMercadopagoOauthRoute: ApiPublicMercadopagoOauthRoute,
  ApiPublicMercadopagoPixRoute: ApiPublicMercadopagoPixRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
