/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as AgendarBarbeiroIdRouteImport } from './routes/agendar.$barbeiroId'
import { Route as AssinarBarbershopIdRouteImport } from './routes/assinar.$barbershopId'
import { Route as AssinaturaConfirmadaSubscriptionIdRouteImport } from './routes/assinatura-confirmada.$subscriptionId'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as PagamentoConfirmadoAppointmentIdRouteImport } from './routes/pagamento-confirmado.$appointmentId'
import { Route as PagamentoAppointmentIdRouteImport } from './routes/pagamento.$appointmentId'
import { Route as ApiCronAppointmentRemindersRouteImport } from './routes/api/cron/appointment-reminders'
import { Route as ApiCronProcessPlanChangesRouteImport } from './routes/api/cron/process-plan-changes'
import { Route as ApiPublicAppointmentCreateRouteImport } from './routes/api/public/appointment-create'
import { Route as ApiPublicAppointmentLocalPaymentRouteImport } from './routes/api/public/appointment-local-payment'
import { Route as ApiPublicAppointmentPushTokenRouteImport } from './routes/api/public/appointment-push-token'
import { Route as ApiPublicBarbershopBySlugRouteImport } from './routes/api/public/barbershop-by-slug'
import { Route as ApiPublicCreateBarbershopRouteImport } from './routes/api/public/create-barbershop'
import { Route as ApiPublicEnsureBarbershopSlugRouteImport } from './routes/api/public/ensure-barbershop-slug'
import { Route as ApiPublicMercadopagoConnectRouteImport } from './routes/api/public/mercadopago-connect'
import { Route as ApiPublicMercadopagoConnectionRouteImport } from './routes/api/public/mercadopago-connection'
import { Route as ApiPublicMercadopagoOauthRouteImport } from './routes/api/public/mercadopago-oauth'
import { Route as ApiPublicMercadopagoPreapprovalRouteImport } from './routes/api/public/mercadopago-preapproval'
import { Route as ApiPublicMercadopagoPreferenceRouteImport } from './routes/api/public/mercadopago-preference'
import { Route as ApiPublicMercadopagoReconcileRouteImport } from './routes/api/public/mercadopago-reconcile'
import { Route as ApiPublicMercadopagoSubscriptionCancelRouteImport } from './routes/api/public/mercadopago-subscription-cancel'
import { Route as ApiPublicMercadopagoSyncRouteImport } from './routes/api/public/mercadopago-sync'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicPlatformSubscriptionCreateRouteImport } from './routes/api/public/platform-subscription-create'
import { Route as ApiPublicPlatformSubscriptionUpgradeRouteImport } from './routes/api/public/platform-subscription-upgrade'
import { Route as ApiPublicSubscriptionStatusRouteImport } from './routes/api/public/subscription-status'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarBarbeiroIdRoute = AgendarBarbeiroIdRouteImport.update({
  id: '/agendar/$barbeiroId',
  path: '/agendar/$barbeiroId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarBarbershopIdRoute = AssinarBarbershopIdRouteImport.update({
  id: '/assinar/$barbershopId',
  path: '/assinar/$barbershopId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaConfirmadaSubscriptionIdRoute =
  AssinaturaConfirmadaSubscriptionIdRouteImport.update({
    id: '/assinatura-confirmada/$subscriptionId',
    path: '/assinatura-confirmada/$subscriptionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmadoAppointmentIdRoute =
  PagamentoConfirmadoAppointmentIdRouteImport.update({
    id: '/pagamento-confirmado/$appointmentId',
    path: '/pagamento-confirmado/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagamentoAppointmentIdRoute = PagamentoAppointmentIdRouteImport.update({
  id: '/pagamento/$appointmentId',
  path: '/pagamento/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAppointmentRemindersRoute =
  ApiCronAppointmentRemindersRouteImport.update({
    id: '/api/cron/appointment-reminders',
    path: '/api/cron/appointment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronProcessPlanChangesRoute =
  ApiCronProcessPlanChangesRouteImport.update({
    id: '/api/cron/process-plan-changes',
    path: '/api/cron/process-plan-changes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppointmentCreateRoute =
  ApiPublicAppointmentCreateRouteImport.update({
    id: '/api/public/appointment-create',
    path: '/api/public/appointment-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppointmentLocalPaymentRoute =
  ApiPublicAppointmentLocalPaymentRouteImport.update({
    id: '/api/public/appointment-local-payment',
    path: '/api/public/appointment-local-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppointmentPushTokenRoute =
  ApiPublicAppointmentPushTokenRouteImport.update({
    id: '/api/public/appointment-push-token',
    path: '/api/public/appointment-push-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBarbershopBySlugRoute =
  ApiPublicBarbershopBySlugRouteImport.update({
    id: '/api/public/barbershop-by-slug',
    path: '/api/public/barbershop-by-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateBarbershopRoute =
  ApiPublicCreateBarbershopRouteImport.update({
    id: '/api/public/create-barbershop',
    path: '/api/public/create-barbershop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEnsureBarbershopSlugRoute =
  ApiPublicEnsureBarbershopSlugRouteImport.update({
    id: '/api/public/ensure-barbershop-slug',
    path: '/api/public/ensure-barbershop-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoConnectRoute =
  ApiPublicMercadopagoConnectRouteImport.update({
    id: '/api/public/mercadopago-connect',
    path: '/api/public/mercadopago-connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoConnectionRoute =
  ApiPublicMercadopagoConnectionRouteImport.update({
    id: '/api/public/mercadopago-connection',
    path: '/api/public/mercadopago-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoOauthRoute =
  ApiPublicMercadopagoOauthRouteImport.update({
    id: '/api/public/mercadopago-oauth',
    path: '/api/public/mercadopago-oauth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoPreapprovalRoute =
  ApiPublicMercadopagoPreapprovalRouteImport.update({
    id: '/api/public/mercadopago-preapproval',
    path: '/api/public/mercadopago-preapproval',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoPreferenceRoute =
  ApiPublicMercadopagoPreferenceRouteImport.update({
    id: '/api/public/mercadopago-preference',
    path: '/api/public/mercadopago-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoReconcileRoute =
  ApiPublicMercadopagoReconcileRouteImport.update({
    id: '/api/public/mercadopago-reconcile',
    path: '/api/public/mercadopago-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoSubscriptionCancelRoute =
  ApiPublicMercadopagoSubscriptionCancelRouteImport.update({
    id: '/api/public/mercadopago-subscription-cancel',
    path: '/api/public/mercadopago-subscription-cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoSyncRoute =
  ApiPublicMercadopagoSyncRouteImport.update({
    id: '/api/public/mercadopago-sync',
    path: '/api/public/mercadopago-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlatformSubscriptionCreateRoute =
  ApiPublicPlatformSubscriptionCreateRouteImport.update({
    id: '/api/public/platform-subscription-create',
    path: '/api/public/platform-subscription-create',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlatformSubscriptionUpgradeRoute =
  ApiPublicPlatformSubscriptionUpgradeRouteImport.update({
    id: '/api/public/platform-subscription-upgrade',
    path: '/api/public/platform-subscription-upgrade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubscriptionStatusRoute =
  ApiPublicSubscriptionStatusRouteImport.update({
    id: '/api/public/subscription-status',
    path: '/api/public/subscription-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comecar': typeof ComecarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/assinar/$barbershopId': typeof AssinarBarbershopIdRoute
  '/assinatura-confirmada/$subscriptionId': typeof AssinaturaConfirmadaSubscriptionIdRoute
  '/b/$slug': typeof BSlugRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/cron/appointment-reminders': typeof ApiCronAppointmentRemindersRoute
  '/api/cron/process-plan-changes': typeof ApiCronProcessPlanChangesRoute
  '/api/public/appointment-create': typeof ApiPublicAppointmentCreateRoute
  '/api/public/appointment-local-payment': typeof ApiPublicAppointmentLocalPaymentRoute
  '/api/public/appointment-push-token': typeof ApiPublicAppointmentPushTokenRoute
  '/api/public/barbershop-by-slug': typeof ApiPublicBarbershopBySlugRoute
  '/api/public/create-barbershop': typeof ApiPublicCreateBarbershopRoute
  '/api/public/ensure-barbershop-slug': typeof ApiPublicEnsureBarbershopSlugRoute
  '/api/public/mercadopago-connect': typeof ApiPublicMercadopagoConnectRoute
  '/api/public/mercadopago-connection': typeof ApiPublicMercadopagoConnectionRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preapproval': typeof ApiPublicMercadopagoPreapprovalRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-subscription-cancel': typeof ApiPublicMercadopagoSubscriptionCancelRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/platform-subscription-create': typeof ApiPublicPlatformSubscriptionCreateRoute
  '/api/public/platform-subscription-upgrade': typeof ApiPublicPlatformSubscriptionUpgradeRoute
  '/api/public/subscription-status': typeof ApiPublicSubscriptionStatusRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comecar': typeof ComecarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/assinar/$barbershopId': typeof AssinarBarbershopIdRoute
  '/assinatura-confirmada/$subscriptionId': typeof AssinaturaConfirmadaSubscriptionIdRoute
  '/b/$slug': typeof BSlugRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/cron/appointment-reminders': typeof ApiCronAppointmentRemindersRoute
  '/api/cron/process-plan-changes': typeof ApiCronProcessPlanChangesRoute
  '/api/public/appointment-create': typeof ApiPublicAppointmentCreateRoute
  '/api/public/appointment-local-payment': typeof ApiPublicAppointmentLocalPaymentRoute
  '/api/public/appointment-push-token': typeof ApiPublicAppointmentPushTokenRoute
  '/api/public/barbershop-by-slug': typeof ApiPublicBarbershopBySlugRoute
  '/api/public/create-barbershop': typeof ApiPublicCreateBarbershopRoute
  '/api/public/ensure-barbershop-slug': typeof ApiPublicEnsureBarbershopSlugRoute
  '/api/public/mercadopago-connect': typeof ApiPublicMercadopagoConnectRoute
  '/api/public/mercadopago-connection': typeof ApiPublicMercadopagoConnectionRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preapproval': typeof ApiPublicMercadopagoPreapprovalRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-subscription-cancel': typeof ApiPublicMercadopagoSubscriptionCancelRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/platform-subscription-create': typeof ApiPublicPlatformSubscriptionCreateRoute
  '/api/public/platform-subscription-upgrade': typeof ApiPublicPlatformSubscriptionUpgradeRoute
  '/api/public/subscription-status': typeof ApiPublicSubscriptionStatusRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comecar': typeof ComecarRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/assinar/$barbershopId': typeof AssinarBarbershopIdRoute
  '/assinatura-confirmada/$subscriptionId': typeof AssinaturaConfirmadaSubscriptionIdRoute
  '/b/$slug': typeof BSlugRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/cron/appointment-reminders': typeof ApiCronAppointmentRemindersRoute
  '/api/cron/process-plan-changes': typeof ApiCronProcessPlanChangesRoute
  '/api/public/appointment-create': typeof ApiPublicAppointmentCreateRoute
  '/api/public/appointment-local-payment': typeof ApiPublicAppointmentLocalPaymentRoute
  '/api/public/appointment-push-token': typeof ApiPublicAppointmentPushTokenRoute
  '/api/public/barbershop-by-slug': typeof ApiPublicBarbershopBySlugRoute
  '/api/public/create-barbershop': typeof ApiPublicCreateBarbershopRoute
  '/api/public/ensure-barbershop-slug': typeof ApiPublicEnsureBarbershopSlugRoute
  '/api/public/mercadopago-connect': typeof ApiPublicMercadopagoConnectRoute
  '/api/public/mercadopago-connection': typeof ApiPublicMercadopagoConnectionRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preapproval': typeof ApiPublicMercadopagoPreapprovalRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-subscription-cancel': typeof ApiPublicMercadopagoSubscriptionCancelRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/platform-subscription-create': typeof ApiPublicPlatformSubscriptionCreateRoute
  '/api/public/platform-subscription-upgrade': typeof ApiPublicPlatformSubscriptionUpgradeRoute
  '/api/public/subscription-status': typeof ApiPublicSubscriptionStatusRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comecar'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/assinar/$barbershopId'
    | '/assinatura-confirmada/$subscriptionId'
    | '/b/$slug'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/cron/appointment-reminders'
    | '/api/cron/process-plan-changes'
    | '/api/public/appointment-create'
    | '/api/public/appointment-local-payment'
    | '/api/public/appointment-push-token'
    | '/api/public/barbershop-by-slug'
    | '/api/public/create-barbershop'
    | '/api/public/ensure-barbershop-slug'
    | '/api/public/mercadopago-connect'
    | '/api/public/mercadopago-connection'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preapproval'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-subscription-cancel'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/public/platform-subscription-create'
    | '/api/public/platform-subscription-upgrade'
    | '/api/public/subscription-status'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comecar'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/assinar/$barbershopId'
    | '/assinatura-confirmada/$subscriptionId'
    | '/b/$slug'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/cron/appointment-reminders'
    | '/api/cron/process-plan-changes'
    | '/api/public/appointment-create'
    | '/api/public/appointment-local-payment'
    | '/api/public/appointment-push-token'
    | '/api/public/barbershop-by-slug'
    | '/api/public/create-barbershop'
    | '/api/public/ensure-barbershop-slug'
    | '/api/public/mercadopago-connect'
    | '/api/public/mercadopago-connection'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preapproval'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-subscription-cancel'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/public/platform-subscription-create'
    | '/api/public/platform-subscription-upgrade'
    | '/api/public/subscription-status'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comecar'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/assinar/$barbershopId'
    | '/assinatura-confirmada/$subscriptionId'
    | '/b/$slug'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/cron/appointment-reminders'
    | '/api/cron/process-plan-changes'
    | '/api/public/appointment-create'
    | '/api/public/appointment-local-payment'
    | '/api/public/appointment-push-token'
    | '/api/public/barbershop-by-slug'
    | '/api/public/create-barbershop'
    | '/api/public/ensure-barbershop-slug'
    | '/api/public/mercadopago-connect'
    | '/api/public/mercadopago-connection'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preapproval'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-subscription-cancel'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/public/platform-subscription-create'
    | '/api/public/platform-subscription-upgrade'
    | '/api/public/subscription-status'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComecarRoute: typeof ComecarRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  PainelRoute: typeof PainelRoute
  AgendarBarbeiroIdRoute: typeof AgendarBarbeiroIdRoute
  AssinarBarbershopIdRoute: typeof AssinarBarbershopIdRoute
  AssinaturaConfirmadaSubscriptionIdRoute: typeof AssinaturaConfirmadaSubscriptionIdRoute
  BSlugRoute: typeof BSlugRoute
  PagamentoConfirmadoAppointmentIdRoute: typeof PagamentoConfirmadoAppointmentIdRoute
  PagamentoAppointmentIdRoute: typeof PagamentoAppointmentIdRoute
  ApiCronAppointmentRemindersRoute: typeof ApiCronAppointmentRemindersRoute
  ApiCronProcessPlanChangesRoute: typeof ApiCronProcessPlanChangesRoute
  ApiPublicAppointmentCreateRoute: typeof ApiPublicAppointmentCreateRoute
  ApiPublicAppointmentLocalPaymentRoute: typeof ApiPublicAppointmentLocalPaymentRoute
  ApiPublicAppointmentPushTokenRoute: typeof ApiPublicAppointmentPushTokenRoute
  ApiPublicBarbershopBySlugRoute: typeof ApiPublicBarbershopBySlugRoute
  ApiPublicCreateBarbershopRoute: typeof ApiPublicCreateBarbershopRoute
  ApiPublicEnsureBarbershopSlugRoute: typeof ApiPublicEnsureBarbershopSlugRoute
  ApiPublicMercadopagoConnectRoute: typeof ApiPublicMercadopagoConnectRoute
  ApiPublicMercadopagoConnectionRoute: typeof ApiPublicMercadopagoConnectionRoute
  ApiPublicMercadopagoOauthRoute: typeof ApiPublicMercadopagoOauthRoute
  ApiPublicMercadopagoPreapprovalRoute: typeof ApiPublicMercadopagoPreapprovalRoute
  ApiPublicMercadopagoPreferenceRoute: typeof ApiPublicMercadopagoPreferenceRoute
  ApiPublicMercadopagoReconcileRoute: typeof ApiPublicMercadopagoReconcileRoute
  ApiPublicMercadopagoSubscriptionCancelRoute: typeof ApiPublicMercadopagoSubscriptionCancelRoute
  ApiPublicMercadopagoSyncRoute: typeof ApiPublicMercadopagoSyncRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicPlatformSubscriptionCreateRoute: typeof ApiPublicPlatformSubscriptionCreateRoute
  ApiPublicPlatformSubscriptionUpgradeRoute: typeof ApiPublicPlatformSubscriptionUpgradeRoute
  ApiPublicSubscriptionStatusRoute: typeof ApiPublicSubscriptionStatusRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$barbeiroId': {
      id: '/agendar/$barbeiroId'
      path: '/agendar/$barbeiroId'
      fullPath: '/agendar/$barbeiroId'
      preLoaderRoute: typeof AgendarBarbeiroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/$barbershopId': {
      id: '/assinar/$barbershopId'
      path: '/assinar/$barbershopId'
      fullPath: '/assinar/$barbershopId'
      preLoaderRoute: typeof AssinarBarbershopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-confirmada/$subscriptionId': {
      id: '/assinatura-confirmada/$subscriptionId'
      path: '/assinatura-confirmada/$subscriptionId'
      fullPath: '/assinatura-confirmada/$subscriptionId'
      preLoaderRoute: typeof AssinaturaConfirmadaSubscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado/$appointmentId': {
      id: '/pagamento-confirmado/$appointmentId'
      path: '/pagamento-confirmado/$appointmentId'
      fullPath: '/pagamento-confirmado/$appointmentId'
      preLoaderRoute: typeof PagamentoConfirmadoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$appointmentId': {
      id: '/pagamento/$appointmentId'
      path: '/pagamento/$appointmentId'
      fullPath: '/pagamento/$appointmentId'
      preLoaderRoute: typeof PagamentoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/appointment-reminders': {
      id: '/api/cron/appointment-reminders'
      path: '/api/cron/appointment-reminders'
      fullPath: '/api/cron/appointment-reminders'
      preLoaderRoute: typeof ApiCronAppointmentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-plan-changes': {
      id: '/api/cron/process-plan-changes'
      path: '/api/cron/process-plan-changes'
      fullPath: '/api/cron/process-plan-changes'
      preLoaderRoute: typeof ApiCronProcessPlanChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment-create': {
      id: '/api/public/appointment-create'
      path: '/api/public/appointment-create'
      fullPath: '/api/public/appointment-create'
      preLoaderRoute: typeof ApiPublicAppointmentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment-local-payment': {
      id: '/api/public/appointment-local-payment'
      path: '/api/public/appointment-local-payment'
      fullPath: '/api/public/appointment-local-payment'
      preLoaderRoute: typeof ApiPublicAppointmentLocalPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment-push-token': {
      id: '/api/public/appointment-push-token'
      path: '/api/public/appointment-push-token'
      fullPath: '/api/public/appointment-push-token'
      preLoaderRoute: typeof ApiPublicAppointmentPushTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/barbershop-by-slug': {
      id: '/api/public/barbershop-by-slug'
      path: '/api/public/barbershop-by-slug'
      fullPath: '/api/public/barbershop-by-slug'
      preLoaderRoute: typeof ApiPublicBarbershopBySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-barbershop': {
      id: '/api/public/create-barbershop'
      path: '/api/public/create-barbershop'
      fullPath: '/api/public/create-barbershop'
      preLoaderRoute: typeof ApiPublicCreateBarbershopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ensure-barbershop-slug': {
      id: '/api/public/ensure-barbershop-slug'
      path: '/api/public/ensure-barbershop-slug'
      fullPath: '/api/public/ensure-barbershop-slug'
      preLoaderRoute: typeof ApiPublicEnsureBarbershopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-connect': {
      id: '/api/public/mercadopago-connect'
      path: '/api/public/mercadopago-connect'
      fullPath: '/api/public/mercadopago-connect'
      preLoaderRoute: typeof ApiPublicMercadopagoConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-connection': {
      id: '/api/public/mercadopago-connection'
      path: '/api/public/mercadopago-connection'
      fullPath: '/api/public/mercadopago-connection'
      preLoaderRoute: typeof ApiPublicMercadopagoConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-oauth': {
      id: '/api/public/mercadopago-oauth'
      path: '/api/public/mercadopago-oauth'
      fullPath: '/api/public/mercadopago-oauth'
      preLoaderRoute: typeof ApiPublicMercadopagoOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-preapproval': {
      id: '/api/public/mercadopago-preapproval'
      path: '/api/public/mercadopago-preapproval'
      fullPath: '/api/public/mercadopago-preapproval'
      preLoaderRoute: typeof ApiPublicMercadopagoPreapprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-preference': {
      id: '/api/public/mercadopago-preference'
      path: '/api/public/mercadopago-preference'
      fullPath: '/api/public/mercadopago-preference'
      preLoaderRoute: typeof ApiPublicMercadopagoPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-reconcile': {
      id: '/api/public/mercadopago-reconcile'
      path: '/api/public/mercadopago-reconcile'
      fullPath: '/api/public/mercadopago-reconcile'
      preLoaderRoute: typeof ApiPublicMercadopagoReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-subscription-cancel': {
      id: '/api/public/mercadopago-subscription-cancel'
      path: '/api/public/mercadopago-subscription-cancel'
      fullPath: '/api/public/mercadopago-subscription-cancel'
      preLoaderRoute: typeof ApiPublicMercadopagoSubscriptionCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-sync': {
      id: '/api/public/mercadopago-sync'
      path: '/api/public/mercadopago-sync'
      fullPath: '/api/public/mercadopago-sync'
      preLoaderRoute: typeof ApiPublicMercadopagoSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/platform-subscription-create': {
      id: '/api/public/platform-subscription-create'
      path: '/api/public/platform-subscription-create'
      fullPath: '/api/public/platform-subscription-create'
      preLoaderRoute: typeof ApiPublicPlatformSubscriptionCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/platform-subscription-upgrade': {
      id: '/api/public/platform-subscription-upgrade'
      path: '/api/public/platform-subscription-upgrade'
      fullPath: '/api/public/platform-subscription-upgrade'
      preLoaderRoute: typeof ApiPublicPlatformSubscriptionUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscription-status': {
      id: '/api/public/subscription-status'
      path: '/api/public/subscription-status'
      fullPath: '/api/public/subscription-status'
      preLoaderRoute: typeof ApiPublicSubscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComecarRoute: ComecarRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  PainelRoute: PainelRoute,
  AgendarBarbeiroIdRoute: AgendarBarbeiroIdRoute,
  AssinarBarbershopIdRoute: AssinarBarbershopIdRoute,
  AssinaturaConfirmadaSubscriptionIdRoute:
    AssinaturaConfirmadaSubscriptionIdRoute,
  BSlugRoute: BSlugRoute,
  PagamentoConfirmadoAppointmentIdRoute: PagamentoConfirmadoAppointmentIdRoute,
  PagamentoAppointmentIdRoute: PagamentoAppointmentIdRoute,
  ApiCronAppointmentRemindersRoute: ApiCronAppointmentRemindersRoute,
  ApiCronProcessPlanChangesRoute: ApiCronProcessPlanChangesRoute,
  ApiPublicAppointmentCreateRoute: ApiPublicAppointmentCreateRoute,
  ApiPublicAppointmentLocalPaymentRoute: ApiPublicAppointmentLocalPaymentRoute,
  ApiPublicAppointmentPushTokenRoute: ApiPublicAppointmentPushTokenRoute,
  ApiPublicBarbershopBySlugRoute: ApiPublicBarbershopBySlugRoute,
  ApiPublicCreateBarbershopRoute: ApiPublicCreateBarbershopRoute,
  ApiPublicEnsureBarbershopSlugRoute: ApiPublicEnsureBarbershopSlugRoute,
  ApiPublicMercadopagoConnectRoute: ApiPublicMercadopagoConnectRoute,
  ApiPublicMercadopagoConnectionRoute: ApiPublicMercadopagoConnectionRoute,
  ApiPublicMercadopagoOauthRoute: ApiPublicMercadopagoOauthRoute,
  ApiPublicMercadopagoPreapprovalRoute: ApiPublicMercadopagoPreapprovalRoute,
  ApiPublicMercadopagoPreferenceRoute: ApiPublicMercadopagoPreferenceRoute,
  ApiPublicMercadopagoReconcileRoute: ApiPublicMercadopagoReconcileRoute,
  ApiPublicMercadopagoSubscriptionCancelRoute:
    ApiPublicMercadopagoSubscriptionCancelRoute,
  ApiPublicMercadopagoSyncRoute: ApiPublicMercadopagoSyncRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicPlatformSubscriptionCreateRoute:
    ApiPublicPlatformSubscriptionCreateRoute,
  ApiPublicPlatformSubscriptionUpgradeRoute:
    ApiPublicPlatformSubscriptionUpgradeRoute,
  ApiPublicSubscriptionStatusRoute: ApiPublicSubscriptionStatusRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
