/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MeusAgendamentosRouteImport } from './routes/meus-agendamentos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as AgendarBarbeiroIdRouteImport } from './routes/agendar.$barbeiroId'
import { Route as PagamentoConfirmadoAppointmentIdRouteImport } from './routes/pagamento-confirmado.$appointmentId'
import { Route as PagamentoAppointmentIdRouteImport } from './routes/pagamento.$appointmentId'
import { Route as ApiPublicMercadopagoOauthRouteImport } from './routes/api/public/mercadopago-oauth'
import { Route as ApiPublicMercadopagoPreferenceRouteImport } from './routes/api/public/mercadopago-preference'
import { Route as ApiPublicMercadopagoReconcileRouteImport } from './routes/api/public/mercadopago-reconcile'
import { Route as ApiPublicMercadopagoStatusRouteImport } from './routes/api/public/mercadopago-status'
import { Route as ApiPublicMercadopagoSyncRouteImport } from './routes/api/public/mercadopago-sync'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusAgendamentosRoute = MeusAgendamentosRouteImport.update({
  id: '/meus-agendamentos',
  path: '/meus-agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarBarbeiroIdRoute = AgendarBarbeiroIdRouteImport.update({
  id: '/agendar/$barbeiroId',
  path: '/agendar/$barbeiroId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmadoAppointmentIdRoute =
  PagamentoConfirmadoAppointmentIdRouteImport.update({
    id: '/pagamento-confirmado/$appointmentId',
    path: '/pagamento-confirmado/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagamentoAppointmentIdRoute = PagamentoAppointmentIdRouteImport.update({
  id: '/pagamento/$appointmentId',
  path: '/pagamento/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoOauthRoute =
  ApiPublicMercadopagoOauthRouteImport.update({
    id: '/api/public/mercadopago-oauth',
    path: '/api/public/mercadopago-oauth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoPreferenceRoute =
  ApiPublicMercadopagoPreferenceRouteImport.update({
    id: '/api/public/mercadopago-preference',
    path: '/api/public/mercadopago-preference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoReconcileRoute =
  ApiPublicMercadopagoReconcileRouteImport.update({
    id: '/api/public/mercadopago-reconcile',
    path: '/api/public/mercadopago-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoStatusRoute =
  ApiPublicMercadopagoStatusRouteImport.update({
    id: '/api/public/mercadopago-status',
    path: '/api/public/mercadopago-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoSyncRoute =
  ApiPublicMercadopagoSyncRouteImport.update({
    id: '/api/public/mercadopago-sync',
    path: '/api/public/mercadopago-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-status': typeof ApiPublicMercadopagoStatusRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-status': typeof ApiPublicMercadopagoStatusRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/meus-agendamentos': typeof MeusAgendamentosRoute
  '/painel': typeof PainelRoute
  '/agendar/$barbeiroId': typeof AgendarBarbeiroIdRoute
  '/pagamento-confirmado/$appointmentId': typeof PagamentoConfirmadoAppointmentIdRoute
  '/pagamento/$appointmentId': typeof PagamentoAppointmentIdRoute
  '/api/public/mercadopago-oauth': typeof ApiPublicMercadopagoOauthRoute
  '/api/public/mercadopago-preference': typeof ApiPublicMercadopagoPreferenceRoute
  '/api/public/mercadopago-reconcile': typeof ApiPublicMercadopagoReconcileRoute
  '/api/public/mercadopago-status': typeof ApiPublicMercadopagoStatusRoute
  '/api/public/mercadopago-sync': typeof ApiPublicMercadopagoSyncRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-status'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-status'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/meus-agendamentos'
    | '/painel'
    | '/agendar/$barbeiroId'
    | '/pagamento-confirmado/$appointmentId'
    | '/pagamento/$appointmentId'
    | '/api/public/mercadopago-oauth'
    | '/api/public/mercadopago-preference'
    | '/api/public/mercadopago-reconcile'
    | '/api/public/mercadopago-status'
    | '/api/public/mercadopago-sync'
    | '/api/public/mercadopago-webhook'
    | '/api/webhooks/mercadopago'
    | '/api/public/webhooks/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MeusAgendamentosRoute: typeof MeusAgendamentosRoute
  PainelRoute: typeof PainelRoute
  AgendarBarbeiroIdRoute: typeof AgendarBarbeiroIdRoute
  PagamentoConfirmadoAppointmentIdRoute: typeof PagamentoConfirmadoAppointmentIdRoute
  PagamentoAppointmentIdRoute: typeof PagamentoAppointmentIdRoute
  ApiPublicMercadopagoOauthRoute: typeof ApiPublicMercadopagoOauthRoute
  ApiPublicMercadopagoPreferenceRoute: typeof ApiPublicMercadopagoPreferenceRoute
  ApiPublicMercadopagoReconcileRoute: typeof ApiPublicMercadopagoReconcileRoute
  ApiPublicMercadopagoStatusRoute: typeof ApiPublicMercadopagoStatusRoute
  ApiPublicMercadopagoSyncRoute: typeof ApiPublicMercadopagoSyncRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-agendamentos': {
      id: '/meus-agendamentos'
      path: '/meus-agendamentos'
      fullPath: '/meus-agendamentos'
      preLoaderRoute: typeof MeusAgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$barbeiroId': {
      id: '/agendar/$barbeiroId'
      path: '/agendar/$barbeiroId'
      fullPath: '/agendar/$barbeiroId'
      preLoaderRoute: typeof AgendarBarbeiroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado/$appointmentId': {
      id: '/pagamento-confirmado/$appointmentId'
      path: '/pagamento-confirmado/$appointmentId'
      fullPath: '/pagamento-confirmado/$appointmentId'
      preLoaderRoute: typeof PagamentoConfirmadoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$appointmentId': {
      id: '/pagamento/$appointmentId'
      path: '/pagamento/$appointmentId'
      fullPath: '/pagamento/$appointmentId'
      preLoaderRoute: typeof PagamentoAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-oauth': {
      id: '/api/public/mercadopago-oauth'
      path: '/api/public/mercadopago-oauth'
      fullPath: '/api/public/mercadopago-oauth'
      preLoaderRoute: typeof ApiPublicMercadopagoOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-preference': {
      id: '/api/public/mercadopago-preference'
      path: '/api/public/mercadopago-preference'
      fullPath: '/api/public/mercadopago-preference'
      preLoaderRoute: typeof ApiPublicMercadopagoPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-reconcile': {
      id: '/api/public/mercadopago-reconcile'
      path: '/api/public/mercadopago-reconcile'
      fullPath: '/api/public/mercadopago-reconcile'
      preLoaderRoute: typeof ApiPublicMercadopagoReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-status': {
      id: '/api/public/mercadopago-status'
      path: '/api/public/mercadopago-status'
      fullPath: '/api/public/mercadopago-status'
      preLoaderRoute: typeof ApiPublicMercadopagoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-sync': {
      id: '/api/public/mercadopago-sync'
      path: '/api/public/mercadopago-sync'
      fullPath: '/api/public/mercadopago-sync'
      preLoaderRoute: typeof ApiPublicMercadopagoSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MeusAgendamentosRoute: MeusAgendamentosRoute,
  PainelRoute: PainelRoute,
  AgendarBarbeiroIdRoute: AgendarBarbeiroIdRoute,
  PagamentoConfirmadoAppointmentIdRoute: PagamentoConfirmadoAppointmentIdRoute,
  PagamentoAppointmentIdRoute: PagamentoAppointmentIdRoute,
  ApiPublicMercadopagoOauthRoute: ApiPublicMercadopagoOauthRoute,
  ApiPublicMercadopagoPreferenceRoute: ApiPublicMercadopagoPreferenceRoute,
  ApiPublicMercadopagoReconcileRoute: ApiPublicMercadopagoReconcileRoute,
  ApiPublicMercadopagoStatusRoute: ApiPublicMercadopagoStatusRoute,
  ApiPublicMercadopagoSyncRoute: ApiPublicMercadopagoSyncRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
